# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhotogrammetyTools
                                 A QGIS plugin
 A plugin for manage photogrammetry projects
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-05
        copyright            : (C) 2019 by Universidad de Castilla-La Mancha
        email                : david.hernandez@uclm.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PhotogrammetyTools class from file PhotogrammetyTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .photogrammetry_tools import PhotogrammetyTools
    return PhotogrammetyTools(iface)
