
# -*- coding: utf-8 -*-
__author__ = 'david.hernandez@uclm.es'

# icons: <div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"             title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"             title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

CONST_SETTINGS_PLUGIN_NAME = "photogrammetry_tools"
CONST_SETTINGS_FILE_NAME = "PhotogrammetryTools.ini"
CONST_PROGRAM_NAME = "Photogrammetry Tools:"
CONST_PROGRAM_TITLE = "Photogrammetry Tools"
CONST_NO_COMBO_SELECT = " ... "
CONST_GRID_SIZE_ACCURACY = 1
CONST_SELECT_ROIS_SHAPEFILES_DIALOG_TITLE = "Select ROIs Shapefiles"
CONST_DOCUMENTS_TYPE_SHAPEFILE = "shp"

CONST_TEMPLATE_PATH = "\\templates"
CONST_SYMBOLOGY_POINT_CLOUD_TEMPLATE = "\\PointCloudsTools.qml"
CONST_SYMBOLOGY_TILES_TEMPLATE = "\\Tiles.qml"
CONST_SYMBOLOGY_ROIS_TEMPLATE = "\\ROIs.qml"
CONST_SYMBOLOGY_IMAGES_PC = "\\images_pc.qml"

CONST_SELECT_IMAGES_FILES_DIALOG_TITLE = "Select Image Files"
CONST_DOCUMENTS_TYPE_JPG = "jpg"
CONST_DOCUMENTS_TYPE_TIF = "tif"
CONST_DOCUMENTS_TYPE_TIFF = "tiff"
CONST_PROJECT_MANAGEMENT_TEMPORAL_PATH = "/temp"
CONST_PROJECT_MANAGEMENT_OUTPUT_PATH = "/output"

CONST_SPATIALITE_LAYERS_TILES_TABLE_NAME = "tiles"
CONST_SPATIALITE_LAYERS_TILES_TABLE_GEOMETRY_COLUMN = "the_geom"

CONST_SPATIALITE_LAYERS_ROIS_TABLE_NAME = "rois"
CONST_SPATIALITE_LAYERS_ROIS_TABLE_GEOMETRY_COLUMN = "the_geom"

CONST_SPATIALITE_LAYERS_IMAGES_PC_TABLE_NAME = "images"
CONST_SPATIALITE_LAYERS_IMAGES_PC_TABLE_NAME_GENERIC_PROJECT = "images_pc"
CONST_SPATIALITE_LAYERS_IMAGES_PC_TABLE_GEOMETRY_COLUMN = "the_geom"

CONST_LAYER_TREE_PROJECT_NAME = "PT: "
CONST_LAYER_TREE_PCTILES_NAME = "Photogrammetric Tiles"

CONST_LAYER_PCTILES_FIELD_ID_NAME = "id"

CONST_METASHAPE_CHUNK_DEFAULT_VALUE = "Chunk 1"
CONST_METASHAPE_CODE_DEFAULT_VALUE = "Prj_1"

CONST_PROJECT_TYPE_GENERIC = "generic"
CONST_PROJECT_TYPE_METASHAPE = "metashape"

CONST_MEASUREMENTS_COMMAND = "Object point measurement"
CONST_EGM08_25_FILE_NAME = "egm08_25.gtx"
CONST_EGM08_25_COMPRESS_FILE_NAME = "egm08_25.7z"

# CONST_LIDARQC_SELECT_INPUT_LIDAR_FILES_DIALOG_TITLE = "Select Lidar files"
# CONST_LIDARQC_DOCUMENTS_TYPE_LAS = "las"
# CONST_LIDARQC_DOCUMENTS_TYPE_LAZ = "laz"
# CONST_LIDARQC_SELECT_INPUT_SHAPEFILES_DIALOG_TITLE = "Select Shapefiles"
# CONST_LIDARQC_DOCUMENTS_TYPE_SHAPEFILE = "shp"
# CONST_LIDARQC_SPATIALITE_DATABASE_TEMPLATE = "/templates/LidarQC_template.sqlite"
# CONST_COMBOBOX_NO_SELECT_OPTION = " ... "
# CONST_LIDARQC_PROJECT_DEFINITION_DIALOG = "Lidar Quality Control - Project Definition"
# CONST_LIDARQC_SELECT_DATA_DIALOG = "Lidar Quality Control - Select Data"
# CONST_LIDARQC_SYMBOLOGY_TEMPLATE = "/templates/LidarQC.qml"
# CONST_LIDARTILES_SYMBOLOGY_TEMPLATE = "/templates/lidartiles.qml"
